---
deployment:
  tasks:
    - export APP="/home/concr/repositories/concre-app"
    - export PHP="/opt/cpanel/ea-php82/root/usr/bin/php"
    - export COMPOSER="/opt/cpanel/composer/bin/composer"

    # Instalar dependencias
    - $COMPOSER --working-dir=$APP install --no-dev --optimize-autoloader

    # Configurar Laravel
    - $PHP $APP/artisan key:generate --force
    - $PHP $APP/artisan migrate --force
    - $PHP $APP/artisan storage:link || true
    - $PHP $APP/artisan optimize:clear
    - $PHP $APP/artisan config:cache
    - $PHP $APP/artisan route:cache
    - $PHP $APP/artisan view:cache

    # Permisos
    - chmod -R ug+rw $APP/storage $APP/bootstrap/cache
