---
deployment:
  tasks:
    # Ruta base del proyecto (repositorio)
    - export DEPLOYPATH="/home/concr/repositories/concre-app"

    # Instalar dependencias
    - /opt/cpanel/composer/bin/composer --working-dir=${DEPLOYPATH} install --no-dev --optimize-autoloader

    # Comandos Laravel (ajusta la versión PHP si no es 8.2)
    - /opt/cpanel/ea-php82/root/usr/bin/php ${DEPLOYPATH}/artisan storage:link || true
    - /opt/cpanel/ea-php82/root/usr/bin/php ${DEPLOYPATH}/artisan migrate --force
    - /opt/cpanel/ea-php82/root/usr/bin/php ${DEPLOYPATH}/artisan optimize:clear
    - /opt/cpanel/ea-php82/root/usr/bin/php ${DEPLOYPATH}/artisan config:cache
    - /opt/cpanel/ea-php82/root/usr/bin/php ${DEPLOYPATH}/artisan route:cache
    - /opt/cpanel/ea-php82/root/usr/bin/php ${DEPLOYPATH}/artisan view:cache

    # Permisos
    - /bin/chmod -R ug+rw ${DEPLOYPATH}/storage ${DEPLOYPATH}/bootstrap/cache
