/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "home": [],
    "dashboard": [],
    "cliente.dashboard": [],
    "proveedor.dashboard": [],
    "empleado.dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "password.edit": [],
    "password.update": [],
    "appearance": [],
    "register": [],
    "register.store": [],
    "login": [],
    "login.store": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.confirm.store": [],
    "logout": [],
    "terceros.index": [],
    "terceros.edit": [
        {
            "name": "tercero",
            "required": true,
            "binding": "id"
        }
    ],
    "gth.empleados.index": [],
    "bascula.index": [],
    "bascula.vehiculosOptions": [],
    "bascula.AlmBasculaOptions": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
