<?php

namespace Database\Seeders\Core\Terceros;

use App\Models\Core\Terceros\Tercero;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Role;

class TerceroSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //Tercero
        DB::table('terceros')->insert([
            'is_active' => 1,
            'identificacion' => 1110582312,
            'nombre1' => 'HR',
            'nombre2' => null,
            'apellido1' => null,
            'apellido2' => null,
            'razon_social' => 'HR',
            'direccion' => null,
            'telefono' => null,
            'email' => null,
            'tipo_documento_id' => 1,
            'tipo_persona_id' => 1,
            'pais_id' => null,
            'departamento_id' => null,
            'municipios_id' => null,
        ]);

        // Crear Varios Terceros
        $terceros = [
            [
'is_active' => 1,
                'identificacion' => 900180449,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'CONCRE TOLIMA SA',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 3,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],
            [
                'is_active' => 1,
                'identificacion' => 900386703,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'A&G ARENAS Y GRAVAS DE COLOMBIA SAS',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 3,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],
            [
                'is_active' => 1,
                'identificacion' => 901089852,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'AGREGADOS ARGOS SAS',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 3,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],
            [
                'is_active' => 1,
                'identificacion' => 900318997,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'AGREGADOS LA SIERRA SA',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 3,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],
            [
                'is_active' => 1,
                'identificacion' => 900722576,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'AGREGADOS MARTINEZ SAS',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 3,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],
            [
                'is_active' => 1,
                'identificacion' => 900263715,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'AGREGADOS NACIONALES SAS',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 3,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],
            [
                'is_active' => 1,
                'identificacion' => 901309061,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'AGREGADOS Y TRANSPORTES DEL TOLIMA SAS',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 3,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],
            [
                'is_active' => 1,
                'identificacion' => 890100251,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'CEMENTOS ARGOS SA',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 3,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],
            [
                'is_active' => 1,
                'identificacion' => 860350697,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'CONCRETOS ARGOS S.A.S',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 3,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],
            [
                'is_active' => 1,
                'identificacion' => 900186724,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'GOLD MACHINERY E.U.',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 3,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],
            [
                'is_active' => 1,
                'identificacion' => 830139442,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'GOLIAT SAS',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 3,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],
            [
                'is_active' => 1,
                'identificacion' => 901098041,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'INVERSIONES TORRES & NIÑO SAS',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 3,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],
            [
                'is_active' => 1,
                'identificacion' => 900405045,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'INVERSIONES Y AGREGADOS SAN ANTONIO S.A.S.',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 3,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],
            [
                'is_active' => 1,
                'identificacion' => 860024586,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'PAVIMENTOS COLOMBIA S.A.S.',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 3,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],
            [
                'is_active' => 1,
                'identificacion' => 900237153,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'TRITURADOS Y VIAS LA CAIMA LTDA',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 3,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],

            [
                'is_active' => 1,
                'identificacion' => 5824752,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'VILLANUEVA GALINDO JORGE ARMANDO',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 1,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],
            [
                'is_active' => 1,
                'identificacion' => 901403919,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'AGREGADOS Y TRITURADOS DEL TOLIMA SAS',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 3,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],
            [
                'is_active' => 1,
                'identificacion' => 900907364,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'EMPRESA COLOMBIANA DE CEMENTOS SAS',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 3,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],
            [
                'is_active' => 1,
                'identificacion' => 901061425,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'PROYECTOS Y SOLUCIONES AMBIENTALES JV SAS',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 3,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],
            [
                'is_active' => 1,
                'identificacion' => 860009808,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'HOLCIM COLOMBIA SA',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 3,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],
            [
                'is_active' => 1,
                'identificacion' => 901214682,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'TRITURADOS DEL RIOS SAS',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 3,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],

            // Trasportistas
            [
                'is_active' => 1,
                'identificacion' => 901370508,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'INVERSIONES CEPG SAS',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 3,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],
[
                'is_active' => 1,
                'identificacion' => 900646465,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'INVERSIONES Y COMMODITIES DE COLOMBIA SAS',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 3,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],
            [
                'is_active' => 1,
                'identificacion' => 900870638,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'FULLTRANS SAS',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 3,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],
             [
                'is_active' => 1,
                'identificacion' => 901880388,
                'nombre1' => null,
                'nombre2' => null,
                'apellido1' => null,
                'apellido2' => null,
                'razon_social' => 'ZZ CARGANDO SAS ',
                'direccion' => null,
                'telefono' => null,
                'email' => null,
                'tipo_documento_id' => 3,
                'tipo_persona_id' => 2,
                'pais_id' => null,
                'departamento_id' => null,
                'municipios_id' => null,
            ],

            //



        ];

        foreach ($terceros as $tercero) {
            Tercero::create($tercero);
        }




        //user
        $user_hr = User::create([
            'name' => 'HR',
            'identificacion' => 1110582312,
            'email' => 'sistemas@concretol.com',
            'password' => bcrypt('1110582312'),
            'tercero_id' => 1,
        ]);


    // Opcional: crea un token personal para pruebas Postman
        if ($user_hr->tokens()->where('name', 'Postman')->doesntExist()) {
            $token = $user_hr->createToken('Postman')->plainTextToken;
            echo "\n🔑 Token HR para Postman:\n{$token}\n\n";
        }
   


        Role::firstOrCreate(['name' => 'Super Admin']);


        $user_hr->assignRole('Super Admin');
/**
 * Crear Permisos
 */
    $permissions = [
        'pcm.bascula.registrobasula.view',

    ];
    foreach ($permissions as $permission) {
        // Crear el permiso si no existe
        \Spatie\Permission\Models\Permission::firstOrCreate(['name' => $permission]);
    }


        $permission = $user_hr->getAllPermissions();

    }
}
