name: Deploy Concre-App (HostGator)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Deploy to HostGator via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /home/concr/cloud.concretol.co

          echo "🔄 Pulling latest code..."
          git fetch --all
          git reset --hard origin/main

          echo "📦 Installing dependencies..."
          composer install --no-dev --optimize-autoloader

          echo "🚀 Running migrations and optimizations..."
          php artisan migrate --force
          php artisan optimize:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

          echo "✅ Deploy complete on $(date)"
